# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "[Cloud] Preview Deploy"

on:
  workflow_call:

env:
  DOTNET_VERSION: "7.0.x" # set this to the dotnet version to use

defaults:
  run:
    working-directory: ./cloud/infrastructure

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: ‚úã Set up mutex
        id: mutex-setup
        run: |
          pushd ../../discrete/Signalco.Discrete.Api.Mutex/node-cli
          npm install
          npm install -g
          npx mutex wait signalcocloudpreview
          popd

      - name: ‚ú® Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: ‚ú® Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 'latest'

      - name: ‚ú® Setup Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm
          cache-dependency-path: ./cloud/infrastructure

      - name: üì¶Ô∏è Installing dependencies
        run: pnpm i --frozen-lockfile

      - name: üîé Determine stack
        shell: bash
        run: |
          [[ $(echo ${BASE_BRANCH#refs/heads/}) = "main" ]] && echo "##[set-output name=branch;]production" || echo "##[set-output name=branch;]$(echo ${BASE_BRANCH#refs/heads/})"
        id: extract_branch
        env:
          BASE_BRANCH: ${{ github.base_ref }}

      - name: ‚ö° Preview Deploy Infrastructure
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: signalco/cloud-primary/${{ steps.extract_branch.outputs.branch }}
          work-dir: ./cloud/infrastructure
          comment-on-pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: ‚úã Release mutex
        if: always() && steps.mutex-setup.outcome == 'success'
        run: |
          pushd ../../discrete/Signalco.Discrete.Api.Mutex/node-cli
          npm install
          npm install -g
          npx mutex release signalcocloudpreview
          popd
