# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "[Web] stories-check"
on:
    pull_request:
        branches: [next, main]
        paths:
          - 'web/**'

defaults:
  run:
    working-directory: ./web

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                version: 'latest'
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  cache: "pnpm"
                  cache-dependency-path: ./web
            - name: Install dependencies
              run: pnpm install --frozen-lockfile --filter=web... --filter=.
            - name: Run stories-check
              run: pnpm stories-check
              id: runStoriesCheck
              continue-on-error: true
              working-directory: web/apps/web/
            - name: Commit changes
              id: ccc
              if: steps.runStoriesCheck.outcome == 'failure'
              uses: EndBug/add-and-commit@v9
              with:
                  add: ".stories-approved"
                  message: "[skip ci] [stories-check] Automated stories changes"
                  new_branch: ${{ github.head_ref }}
                  default_author: github_actions
              env:
                  GITHUB_TOKEN: ${{ secrets.AT_GH_CD_REPO_PAT }}
